### ISSUE TITLE
Use rpminspect xunit output and simplify rpminspect.fmf

### ISSUE THREAD

**Issue by dcantrell** [fedora-ci/rpminspect-pipeline#13]
In rpminspect.fmf, should the discover section just become:

```
discover:
    how: shell
    tests:
    - name: rpminspect
      test: /usr/local/bin/rpminspect_runner.sh $TASK_ID $RELEASE_ID
      duration: 120m
```

?

The rpminspect_runner.sh script should also change to output xunit using ```-F xunit```.  And the runner script can also lose all the handling for the test being specified and the downloading since all that could be pushed off to rpminspect now.  What else is required here for the output?
